### ISSUE TITLE
Typings issue in v3.3.0

### ISSUE THREAD

**Issue by AndrewLeedham** [cenk1cenk2/listr2#276]
When using Listr2 in a TypeScript project I am getting the following TSC error when using v3.3.0:
```
../../node_modules/listr2/dist/lib/task-wrapper.d.ts:27:5 - error TS2416: Property 'run' in type 'TaskWrapper<Ctx, Renderer>' is not assignable to the same property in base type 'ListrTaskWrapper<Ctx, Renderer>'.
  Type '(ctx: Ctx) => Promise<void>' is not assignable to type '(ctx?: Ctx | undefined, task?: ListrTaskWrapper<Ctx, Renderer> | undefined) => Promise<void>'.
    Types of parameters 'ctx' and 'ctx' are incompatible.
      Type 'Ctx | undefined' is not assignable to type 'Ctx'.
        'Ctx' could be instantiated with an arbitrary type which could be unrelated to 'Ctx | undefined'.
          Type 'undefined' is not assignable to type 'Ctx'.
            'Ctx' could be instantiated with an arbitrary type which could be unrelated to 'undefined'.

27     run(ctx: Ctx): Promise<void>;
```
It compiles fine with the previous v3.2.3.

**Comment by cenk1cenk2** [comment]
Is strict null checks enabled? I have not made any substantial changes to types. But i will have a look at it. Sorry for inconvience.

**Comment by cenk1cenk2** [comment]
Oh okay I might have an idea because i swapped legacy styled function typings to arrow typings maybe that can be the cause.

**Comment by AndrewLeedham** [comment]
> Is strict null checks enabled? I have not made any substantial changes to types. But i will have a look at it. Sorry for inconvience.

I have `strict` enabled, which I believe includes that so yes. My tsconfig roughly looks like this:
```
    "target": "ES2019",
    "module": "CommonJS",
    "moduleResolution": "node",
    "declaration": false,
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "jsx": "preserve",
```

**Comment by cenk1cenk2** [comment]
I see. Tommorrow i will take a look at this and revert back to original non arrow form of typings and release it on beta. If this was working before with the same tsconfig then it would be worth the try.

**Comment by karlhorky** [comment]
@AndrewLeedham did you add any annotations to your task function? (if so, can you post your code for the failing task?)

I'm using the new version and haven't seen any type errors...

**Comment by AndrewLeedham** [comment]
Just running it with:
```
const tasks = new Listr([]);
tasks.run();
```
throws the error.

I am using TS 4.1.3 and node 14.15.0 if that helps.

**Comment by cenk1cenk2** [comment]
Can you check out the latest alpha package, I just rollbacked the types I did, since it is basically the same thing.

**Comment by AndrewLeedham** [comment]
Still seeing the same issue with `3.3.1-beta.1`.

**Comment by cenk1cenk2** [comment]
Oh, that's sad.

So going through it:
- It does work with the prior version of 3.2.3 and does not work with 3.3.0 or the beta.

Can you create me a minimum reproducible repo whenever you have some extra time?

**Comment by AndrewLeedham** [comment]
Sure: if you click Run at the top of https://repl.it/@AndrewLeedham56/List2-repro the error is returned from `tsc`. Worth noting here I am only seeing the issue via tsc locally as well, the VSCode language server is not picking it up :/

**Comment by appkaiju** [comment]
Hi, @cenk1cenk2. Do you think that changing TaskWrapper.d.ts to `run(ctx: Ctx | undefined): Promise<void>;`. would be enough? I don't see any issues with it.

**Comment by cenk1cenk2** [comment]
Mr. @appkaiju, I tried that some other way setting the default context to `any | undefined` because it gets injected from the main class to the task wrapper, but the combination of that with converting run from arrow function seems to solve the issue. I will merge it to the main branch now.

https://repl.it/@CenkKl/List2-repro#index.js

**Comment by AndrewLeedham** [comment]
@cenk1cenk2 this works perfectly thank you!
